[project]
authors = [
  { name = "Denrei Keith De Jesus", email = "denreikeith@gmail.com" },
  { name = "Stephanie Palero", email = "s.palero.526878@umindanao.edu.ph" },
  { name = "Joshua Roi Nomus", email = "j.nomus.523625@umindanao.edu.ph" },
]
name = "MiRAG"
version = "0.1.0"
description = "Mind the (Context) Gap: Reducing AI Hallucination by Bridging Long-Context Retrieval and Information Refinement through Mindful RAG"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "accelerate>=1.3.0",
    "datasets>=3.2.0",
    "google-genai>=1.0.0",
    "huggingface-hub>=0.28.1",
    "numpy>=2.2.2",
    "python-dotenv>=1.0.1",
    "tevatron>=0.1.0",
    "tiktoken>=0.8.0",
    "tqdm>=4.67.1",
    "transformers>=4.48.3",
    "wikiextractor",
]

[dependency-groups]
lint =  [
"ruff>=0.9.5"
]
dev = [
    "icecream>=2.1.4",
    "torch>=2.6.0",
]

[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[tool.uv.sources]
wikiextractor = { git = "https://github.com/attardi/wikiextractor.git", rev = "ab8988ebfa9e4557411f3d4c0f4ccda139e18875" }
